version: "3.7"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
        - ..:/workspace
  gra:
    image: grafana/grafana
    ports:
        - "3000:3000"
  db:
    image: mysql
    ports:
        - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    ports:
        - 8080:8080